version: "3.8"

services:
  users-data:
    restart: always
    build: .
    image: users-data
    ports: 
      - 58083:8080
    env_file: 
      - .env
    networks: 
      - products-store

networks:
  products-store:
    name: products-store
    driver: bridge
