version: "3.8"

services:
  products-list:
    restart: always
    build: .
    image: products-list
    ports: 
      - 58081:8080
    env_file:
      - .env
    networks:
      - products-store

networks:
  products-store:
    name: products-store
    driver: bridge
