// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        (unknown)
// source: protobuf/proto/productslist/products_list.proto

package productslist

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// ProductRequest represents the request message for product reading interactions
type ProductsListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *ProductsListRequest) Reset() {
	*x = ProductsListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_productslist_products_list_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductsListRequest) ProtoMessage() {}

func (x *ProductsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_productslist_products_list_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductsListRequest.ProtoReflect.Descriptor instead.
func (*ProductsListRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_productslist_products_list_proto_rawDescGZIP(), []int{0}
}

func (x *ProductsListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// ProductResponse represents the response message for product reading requests
type ProductsListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string                         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PriceInCents int32                          `protobuf:"varint,2,opt,name=price_in_cents,json=priceInCents,proto3" json:"price_in_cents,omitempty"`
	Tilte        string                         `protobuf:"bytes,3,opt,name=tilte,proto3" json:"tilte,omitempty"`
	Description  string                         `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Discount     *ProductsListResponse_Discount `protobuf:"bytes,5,opt,name=discount,proto3" json:"discount,omitempty"`
}

func (x *ProductsListResponse) Reset() {
	*x = ProductsListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_productslist_products_list_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductsListResponse) ProtoMessage() {}

func (x *ProductsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_productslist_products_list_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductsListResponse.ProtoReflect.Descriptor instead.
func (*ProductsListResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_productslist_products_list_proto_rawDescGZIP(), []int{1}
}

func (x *ProductsListResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductsListResponse) GetPriceInCents() int32 {
	if x != nil {
		return x.PriceInCents
	}
	return 0
}

func (x *ProductsListResponse) GetTilte() string {
	if x != nil {
		return x.Tilte
	}
	return ""
}

func (x *ProductsListResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductsListResponse) GetDiscount() *ProductsListResponse_Discount {
	if x != nil {
		return x.Discount
	}
	return nil
}

type ProductsListResponse_Discount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pct          float32 `protobuf:"fixed32,1,opt,name=pct,proto3" json:"pct,omitempty"`
	ValueInCents int32   `protobuf:"varint,2,opt,name=value_in_cents,json=valueInCents,proto3" json:"value_in_cents,omitempty"`
}

func (x *ProductsListResponse_Discount) Reset() {
	*x = ProductsListResponse_Discount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_productslist_products_list_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductsListResponse_Discount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductsListResponse_Discount) ProtoMessage() {}

func (x *ProductsListResponse_Discount) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_productslist_products_list_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductsListResponse_Discount.ProtoReflect.Descriptor instead.
func (*ProductsListResponse_Discount) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_productslist_products_list_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ProductsListResponse_Discount) GetPct() float32 {
	if x != nil {
		return x.Pct
	}
	return 0
}

func (x *ProductsListResponse_Discount) GetValueInCents() int32 {
	if x != nil {
		return x.ValueInCents
	}
	return 0
}

var File_protobuf_proto_productslist_products_list_proto protoreflect.FileDescriptor

var file_protobuf_proto_productslist_products_list_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x6c, 0x69, 0x73, 0x74, 0x2f, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x6c, 0x69, 0x73, 0x74, 0x22,
	0x2e, 0x0a, 0x13, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x91, 0x02, 0x0a, 0x14, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x5f, 0x69, 0x6e, 0x5f, 0x63, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x70, 0x72, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x43, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x6c, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x6c, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x47, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x73, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x69, 0x73,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x08, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x1a,
	0x42, 0x0a, 0x08, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x70,
	0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x70, 0x63, 0x74, 0x12, 0x24, 0x0a,
	0x0e, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x69, 0x6e, 0x5f, 0x63, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x49, 0x6e, 0x43, 0x65,
	0x6e, 0x74, 0x73, 0x32, 0x69, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x59, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x73, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x6c, 0x69,
	0x73, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x73, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x65,
	0x0a, 0x2f, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x7a, 0x65, 0x72,
	0x6f, 0x62, 0x65, 0x72, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x6c, 0x69, 0x73,
	0x74, 0x50, 0x01, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x7a, 0x65, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x73, 0x2d, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x73, 0x6c, 0x69, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_proto_productslist_products_list_proto_rawDescOnce sync.Once
	file_protobuf_proto_productslist_products_list_proto_rawDescData = file_protobuf_proto_productslist_products_list_proto_rawDesc
)

func file_protobuf_proto_productslist_products_list_proto_rawDescGZIP() []byte {
	file_protobuf_proto_productslist_products_list_proto_rawDescOnce.Do(func() {
		file_protobuf_proto_productslist_products_list_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_proto_productslist_products_list_proto_rawDescData)
	})
	return file_protobuf_proto_productslist_products_list_proto_rawDescData
}

var file_protobuf_proto_productslist_products_list_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protobuf_proto_productslist_products_list_proto_goTypes = []interface{}{
	(*ProductsListRequest)(nil),           // 0: productslist.ProductsListRequest
	(*ProductsListResponse)(nil),          // 1: productslist.ProductsListResponse
	(*ProductsListResponse_Discount)(nil), // 2: productslist.ProductsListResponse.Discount
}
var file_protobuf_proto_productslist_products_list_proto_depIdxs = []int32{
	2, // 0: productslist.ProductsListResponse.discount:type_name -> productslist.ProductsListResponse.Discount
	0, // 1: productslist.ProductsList.ListProducts:input_type -> productslist.ProductsListRequest
	1, // 2: productslist.ProductsList.ListProducts:output_type -> productslist.ProductsListResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_proto_productslist_products_list_proto_init() }
func file_protobuf_proto_productslist_products_list_proto_init() {
	if File_protobuf_proto_productslist_products_list_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_proto_productslist_products_list_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductsListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_productslist_products_list_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductsListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_productslist_products_list_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductsListResponse_Discount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_proto_productslist_products_list_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_proto_productslist_products_list_proto_goTypes,
		DependencyIndexes: file_protobuf_proto_productslist_products_list_proto_depIdxs,
		MessageInfos:      file_protobuf_proto_productslist_products_list_proto_msgTypes,
	}.Build()
	File_protobuf_proto_productslist_products_list_proto = out.File
	file_protobuf_proto_productslist_products_list_proto_rawDesc = nil
	file_protobuf_proto_productslist_products_list_proto_goTypes = nil
	file_protobuf_proto_productslist_products_list_proto_depIdxs = nil
}
