dataStore:
  product:
    type: nosql
    host: products-list
    port: 27017
    database: products
    databaseType: mongo
    auth:
      type: env
      user: PRODUCTS_MONGO_DB_USERNAME
      pass: PRODUCTS_MONGO_DB_PASSWORD
      repo: admin
  user:
    type: grpc
    host: users-data
    port: 8080
server:
  port: 8080
