dataStore:
  product:
    type: nosql
    host: localhost
    port: 47017
    database: products
    databaseType: mongodb
    auth:
      type: plain
      user: root
      pass: insecure
      repo: admin
  user:
    type: grpc
    host: localhost
    port: 58083
server:
  port: 8080
