grpcServerConfig:
  productConfig:
    port: 58081
grpcClientConfig:
  discountConfig:
    host: http://localhost
    port: 58082
useCaseConfig:
  productConfig:
    dsConfig:
      type: mongo
      host: localhost:47017
      database: products
      auth:
        type: plain
        user: root
        pass: insecure
        repo: admin
  discountConfig:
    dsConfig:
      type: grpc
      host: http://localhost:58082
