grpcServerConfig:
  productConfig:
    port: 8080
grpcClientConfig:
  discountConfig:
    host: http://localhost
    port: 58082
useCaseConfig:
  productConfig:
    dsConfig:
      type: mongo
      host: product-db:27017
      database: products
      auth:
        type: env
        user: PRODUCTS_MONGO_DB_USERNAME
        pass: PRODUCTS_MONGO_DB_PASSWORD
        repo: admin
  discountConfig:
    dsConfig:
      type: grpc
      host: http://localhost:58082
