version: "3.8"

services:
  user-db:
    image: postgres
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: user_db
    ports: 
      - 5432:5432
    volumes:
      - ./user_db:/docker-entrypoint-initdb.d
      - /containers/postgresql:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 9900:8080

  product-db:
    image: mongo
    environment: 
      MONGO_INITDB_DATABASE: products
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: insecure
    ports:
      - 27017:27017
    volumes:
      - ./product_db:/docker-entrypoint-initdb.d
      - /containers/mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9901:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: product-db
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: insecure
