version: "3.8"

services:
  product-db:
    image: mongo:4.4.1-bionic
    environment: 
      MONGO_INITDB_DATABASE: products
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: insecure
    ports:
      - 47017:27017
    volumes:
      - ./product_db:/docker-entrypoint-initdb.d
      - /containers/mongo:/data/db
    networks: 
      - products-store
      
  user-db:
    image: postgres:12
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: user_db
    ports: 
      - 45432:5432
    volumes:
      - ./user_db:/docker-entrypoint-initdb.d
      - /containers/postgresql:/var/lib/postgresql/data
    networks: 
      - products-store

  adminer:
    image: adminer:4.7.7-standalone
    restart: always
    ports:
      - 48080:8080
    networks: 
      - products-store

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 48081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: product-db
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: insecure
    networks: 
      - products-store

networks:
  products-store:
    name: products-store
    driver: bridge
