dataStore:
  sql:
    userInfo:
      type: postgres
      host: localhost
      port: 45432
      database: user_info
      auth:
        type: plain
        user: root
        pass: insecure
server:
  port: 8080
