dataStore:
  userInfo:
    type: sql
    host: localhost
    port: 45432
    database: user_info
    databaseType: postgres
    auth:
      type: plain
      user: root
      pass: insecure
server:
  port: 8080
